# Generated by Django 4.1 on 2022-08-23 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('name', models.CharField(default='-', max_length=255)),
                ('u_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='12345678', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('age', models.CharField(default='-', max_length=255)),
                ('email', models.CharField(default='-', max_length=255)),
                ('ph_no', models.CharField(default='-', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(auto_created=True, default=False, max_length=255)),
                ('date', models.CharField(auto_created=True, default=datetime.date(2022, 8, 23), max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
            ],
        ),
    ]
