# Generated by Django 4.1 on 2022-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_credentials_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='id',
        ),
        migrations.AlterField(
            model_name='credentials',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='u_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
