# Generated by Django 4.1 on 2023-01-10 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_remove_credentials_id_alter_credentials_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='dept',
            field=models.CharField(default='Client', max_length=255),
        ),
        migrations.AddField(
            model_name='todo',
            name='dept',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 1, 10), max_length=255),
        ),
    ]
