# Generated by Django 4.1 on 2023-01-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_credentials_dept_todo_dept_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dept',
            field=models.CharField(blank='False', default='Unsorted', max_length=255),
        ),
    ]
