# Generated by Django 4.1 on 2023-01-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_alter_todo_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dept',
            new_name='department',
        ),
    ]
