# Generated by Django 4.1 on 2023-01-15 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_rename_dept_todo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 1, 15), max_length=255),
        ),
    ]
