# Generated by Django 4.1 on 2023-01-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_todo_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
