# Generated by Django 4.1 on 2023-01-16 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_delete_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='email',
            field=models.CharField(default='Not Given', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 1, 16), max_length=255),
        ),
    ]
