# Generated by Django 4.1 on 2023-01-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_credentials_email_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 1, 17), max_length=255),
        ),
    ]
