# Generated by Django 4.1 on 2023-02-02 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_todo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='task_subject',
        ),
        migrations.AddField(
            model_name='credentials',
            name='unit',
            field=models.CharField(default='Unsorted', max_length=255),
        ),
        migrations.AddField(
            model_name='todo',
            name='remark',
            field=models.CharField(auto_created=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_dets',
            field=models.CharField(auto_created=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='todo',
            name='unit',
            field=models.CharField(default='Unsorted', max_length=255),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.CharField(default='1234', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 2, 2), max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='department',
            field=models.CharField(default='Unsorted', max_length=255),
        ),
    ]
