# Generated by Django 4.1 on 2023-02-11 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_rename_task_todo_task_subject_credentials_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 2, 11), max_length=255),
        ),
    ]
