# Generated by Django 4.1 on 2023-02-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='unit',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
