# Generated by Django 4.1 on 2023-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_alter_credentials_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='unit',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
