# Generated by Django 4.1 on 2023-05-05 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_credentials_phone_alter_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='emp_id',
            field=models.CharField(default='Not Given', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='emp_id',
            field=models.CharField(default='Not Given', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 5, 5), max_length=255),
        ),
    ]
