# Generated by Django 4.1 on 2023-05-14 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_credentials_emp_id_todo_emp_id_alter_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='phone',
            field=models.CharField(default='Not Given', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 5, 14), max_length=255),
        ),
    ]
