# Generated by Django 4.1 on 2023-05-29 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_todo_phone_alter_todo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('emp_id', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=255)),
                ('task_subject', models.CharField(max_length=255)),
                ('task_dets', models.CharField(max_length=2000)),
                ('progress', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 5, 29), max_length=255),
        ),
    ]
