# Generated by Django 4.1 on 2023-06-08 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0019_complaints_alter_todo_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.AddField(
            model_name='credentials',
            name='status',
            field=models.CharField(auto_created=True, default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='todo',
            name='closed',
            field=models.CharField(auto_created=True, default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='feedback',
            field=models.CharField(auto_created=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 6, 8), max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='emp_id',
            field=models.CharField(default='Not Given', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='progress',
            field=models.CharField(auto_created=True, default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='remark',
            field=models.CharField(auto_created=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='unit',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
