# Generated by Django 4.1 on 2023-06-09 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0020_delete_complaints_credentials_status_todo_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(auto_created=True, default='Unassigned', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(auto_created=True, default=datetime.date(2023, 6, 10), max_length=100),
        ),
    ]
